# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron: 30 14 * * 4

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     
      - name: pull collection from remote repository
        uses: actions/checkout@v4
        
      - name: install Node.js
        uses: actions/setup-node@v4
        
      - name: install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-html
      
      - name: Run postman collection
        run: 'newman run Trello_API_Testing.postman_collection.json -e Trello_environment.postman_environment.json -r cli,html --reporter-html-export report.html' 

     
      - name: check files
        run: 'ls'
        